library(tidyverse)   

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
current_directory <- getwd()
df <- read_csv(file.path(current_directory, "Retail_StoreDataset.csv"))
head(df, 5)
summary(df)
glimpse(df)
colSums(is.na(df))
df <- df |> drop_na()
summary(df)
write_csv(df, "cleaned_retail_sales_data.csv")
